Repository ToLoad/memory-box, pull requests merged in 2022-10, with the labels that each got.

#5 Next.js PWA 기능 추가
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.jsx
  frontend/pages/_document.jsx
  frontend/public/android-icon-192x192.png
  frontend/public/apple-icon-180x180.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon-96x96.png
  frontend/public/icon-128x128.png
  frontend/public/icon-144x144.png
  frontend/public/icon-152x152.png
  frontend/public/icon-192x192.png
  frontend/public/icon-384x384.png
  frontend/public/icon-48x48.png
  frontend/public/icon-512x512.png
  frontend/public/icon-72x72.png
  frontend/public/icon-96x96.png
  frontend/public/manifest.json
  frontend/public/ms-icon-144x144.png
  frontend/public/sw.js
  frontend/public/sw.js.map
  frontend/public/workbox-eac1af49.js
  frontend/public/workbox-eac1af49.js.map
Labels: feature, frontend

#6 Github PR 템플릿 추가
  .github/pull_request_template.md
  .gitlab/merge_request_templates/default.md
Labels: documentation

#8 v1.0.4 배포
  .github/pull_request_template.md
  .gitlab/merge_request_templates/default.md
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/src/main/java/kr/guards/memorybox/domain/box/controller/BoxController.java
  backend/src/test/java/kr/guards/memorybox/domain/box/controller/BoxControllerTest.java
  backend/src/test/java/kr/guards/memorybox/domain/box/service/BoxServiceTest.java
  backend/src/test/java/kr/guards/memorybox/utils/MockAuthentication.java
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.jsx
  frontend/pages/_document.jsx
  frontend/public/android-icon-192x192.png
  frontend/public/apple-icon-180x180.png
  frontend/public/favicon-16x16.png
  frontend/public/favicon-32x32.png
  frontend/public/favicon-96x96.png
  frontend/public/icon-128x128.png
  frontend/public/icon-144x144.png
  frontend/public/icon-152x152.png
  frontend/public/icon-192x192.png
  frontend/public/icon-384x384.png
  frontend/public/icon-48x48.png
  frontend/public/icon-512x512.png
  frontend/public/icon-72x72.png
  frontend/public/icon-96x96.png
  frontend/public/manifest.json
  frontend/public/ms-icon-144x144.png
  frontend/public/sw.js
  frontend/public/sw.js.map
  frontend/public/workbox-eac1af49.js
  frontend/public/workbox-eac1af49.js.map
Labels: release

#9 ClientStorage 변경
  frontend/api/index.js
  frontend/api/user.js
  frontend/components/Box/Box.jsx
  frontend/components/Login/JoinUserLogin.jsx
  frontend/components/Main/MainPage.jsx
  frontend/components/Mypage/EditInfo.jsx
  frontend/components/Mypage/MyPage.jsx
  frontend/components/Navbar/RightNav.jsx
  frontend/components/Slick/SlickOpen.jsx
  frontend/components/Slick/SlickReady.jsx
  frontend/pages/kakao/callback.jsx
  frontend/pages/register/[id].jsx
Labels: frontend, fix

#10 v1.1 배포
  frontend/api/index.js
  frontend/api/user.js
  frontend/components/Box/Box.jsx
  frontend/components/Login/JoinUserLogin.jsx
  frontend/components/Main/MainPage.jsx
  frontend/components/Mypage/EditInfo.jsx
  frontend/components/Mypage/MyPage.jsx
  frontend/components/Navbar/RightNav.jsx
  frontend/components/Slick/SlickOpen.jsx
  frontend/components/Slick/SlickReady.jsx
  frontend/pages/kakao/callback.jsx
  frontend/pages/register/[id].jsx
Labels: release
